pinyin: depends on pthread
Fix compilation error:
userdict.cpp: undefined reference to `pthread_mutex_trylock'

Change-Id: I1e067f2c047a2139f4b3d0f8d2ae404ca362157f
Reviewed-by: Mitch Curtis <mitch.curtis@qt.io>